### ISSUE TITLE
make all failed : libcaffe.so.1.0.0-rc3

### ISSUE THREAD

**Issue by mdamircoder** [Zhouaojun/Incremental-Network-Quantization#30]
make all is failed, showing the following error.

AR -o .build_release/lib/libcaffe.a
**LD -o .build_release/lib/libcaffe.so.1.0.0-rc3**
/usr/bin/ld: cannot find -lfftw3f
/usr/bin/ld: cannot find -lfftw3
/usr/bin/ld: cannot find -lfftw3f_omp
collect2: error: ld returned 1 exit status
**Makefile:581**: recipe for target '.build_release/lib/**libcaffe.so.1.0.0-rc3**' failed
make: *** [.build_release/lib/libcaffe.so.1.0.0-rc3] Error 1

**Comment by mdamircoder** [comment]
Solved 
Install libfftw3-dev
**sudo apt-get install libfftw3-dev**

**Comment by mdamirsohail13** [comment]
Just 
Installed libfftw3-dev
