### ISSUE TITLE
Where is the code about setting the partial propagation of weights in a specific layer？

### ISSUE THREAD

**Issue by KangolHsu** [Zhouaojun/Incremental-Network-Quantization#4]
Thanks for your code。Could you specify Where is the code about setting the partial propagation of weights in a specific layer？

**Comment by Zhouaojun** [comment]
line 235 in https://github.com/Zhouaojun/Incremental-Network-Quantization/blob/master/src/caffe/solvers/sgd_solver.cpp

**Comment by KangolHsu** [comment]
https://github.com/Zhouaojun/Incremental-Network-Quantization/blob/0548e144898ff5d6d6906ef7ea862bf5e01989f9/src/caffe/solvers/sgd_solver.cpp#L235
